/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [TableID]
      ,[FirstName]
      ,[LastName]
      ,[Id]
      ,[City]
      ,[Steet]
      ,[Bildingnumber]
      ,[Birthday]
      ,[Phone]
      ,[Cellphone]
      ,[AvaccinDate]
      ,[Atipevaccin]
      ,[Sickdate]
      ,[Recoverydate]
      ,[BvaccindDate]
      ,[CvaccinDate]
      ,[DvaccinDate]
      ,[Btipevaccin]
      ,[Dtipevaccin]
      ,[Ctipevaccin]
  FROM [covid].[dbo].[Members11]
  where Id='1234'